### ISSUE TITLE
Make clientSecret optional in Connect-Dracoon

### ISSUE THREAD

**Issue by unbekanntes-pferd** [Callidus2000/Dracoon#5]
DRACOON also supports the usage of clients with no client secret, specifically for scripting via DRACOON Legacy Scripting. 
With current DRACOON versions, the DRACOON Legacy Scripting client (client id: dracoon_legacy_scripting) allows access via password flow and has no secret (empty string ""). 
If no client secret is provided, an empty string should be passed (""). 
Currently, when trying to set the client secret to an empty string,  the process fails:

`Request-DracoonOAuthToken: Cannot bind argument to parameter 'ClientSecret' because it is an empty string.`
I assume this is due to the mandatory flag of the parameter.

**Comment by Callidus2000** [comment]
## Just released v1.5.1 which implements the proposed change.

As a background: We've updated our onPrem Docker-LTSC-Version to the latest version of Dracoon Server. With this release the "DRACOON Legacy Scripting client" can be enabled. The ClientSecret Parameter was converted to a dynamic parameter to achieve the best option.
